# Generated by Django 3.1.3 on 2021-01-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nom du type de vérification')),
            ],
            options={
                'verbose_name': 'Type de vérification',
                'verbose_name_plural': 'Types de vérification',
                'ordering': ('name',),
            },
        ),
    ]
