# Generated by Django 3.1.3 on 2021-01-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_types', '0003_auto_20210117_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtype',
            name='code',
            field=models.CharField(default='HTTP', max_length=4, unique=True, verbose_name='Identifiant unique du type de vérification'),
        ),
    ]
