# Generated by Django 3.1.3 on 2021-01-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_types', '0006_auto_20210118_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtype',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, unique=True, verbose_name='Identifiant unique du type de vérification'),
        ),
    ]
