# Generated by Django 3.1.3 on 2021-01-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification_types', '0008_auto_20210118_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtype',
            name='code',
        ),
    ]
