# Generated by Django 3.1.3 on 2021-01-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_types', '0010_verificationtype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtype',
            name='code',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='Identifiant unique'),
        ),
        migrations.AlterField(
            model_name='verificationtype',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Type de vérification'),
        ),
    ]
