# Generated by Django 3.1.3 on 2021-01-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_types', '0011_auto_20210118_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtype',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Description du type de vérification'),
        ),
    ]
