# Generated by Django 3.1.3 on 2021-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_types', '0013_auto_20210118_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Type de vérification'),
        ),
    ]
