# Generated by Django 3.1.3 on 2021-01-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Titre de la vérification')),
                ('url', models.CharField(default=None, max_length=255, verbose_name='Url à vérifier')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ('title',),
            },
        ),
    ]
