# Generated by Django 3.1.3 on 2021-01-17 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verification_types', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('verification_option', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Option de vérification')),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Page à vérifier')),
                ('verification_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='verification_types.verificationtype', verbose_name='Type de vérification')),
            ],
            options={
                'verbose_name': 'Vérification',
                'verbose_name_plural': 'Vérifications',
                'ordering': ('page', 'verification_type'),
            },
        ),
    ]
